language: java
jdk:
- openjdk8
after_success: chmod +x tool-model.py && ./tool-model.py
before_install:
- openssl aes-256-cbc -K $encrypted_ff9119226831_key -iv $encrypted_ff9119226831_iv
  -in id_rsa_travis.enc -out id_rsa_travis -d
- openssl aes-256-cbc -K $encrypted_ba8ee1c4b196_key -iv $encrypted_ba8ee1c4b196_iv
  -in id_rsa_travis.enc -out id_rsa_travis -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa_travis
- ssh-add id_rsa_travis
install: mvn clean install -DskipTests=true -Drat.skip=true -Dmaven.javadoc.skip=true
  -B -V
